import Head from 'next/head';
import { Card } from '../components/Card';
import { Header } from '../components/Header';
import { Footer } from '../components/Footer';
import { Bar } from '../components/Bar';
import { useEffect } from 'react';
import { useState } from 'react';

export default function Home({ data }) {
  const [selected, setSelected] = useState('lp');

  const [ranking, setRanking] = useState(data);

  const sortRanking = () => {
    if (selected == 'lp') {
      setRanking((ranking) => ranking.sort((a, b) => b.progress - a.progress));
    } else if (selected == 'progress') {
      setRanking((ranking) => ranking.sort((a, b) => b.lp - a.lp));
    } else {
      setRanking((ranking) => ranking.sort((a, b) => a.position - b.position));
    }
  };

  useEffect(() => {
    sortRanking();
  }, [selected]);

  return (
    <>
      <Head>
        <title>GRANDMASTER CHALLENGE</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <Header />
      <Bar selected={selected} setSelected={setSelected} />
      <div className='grid grid-col grid-cols-1 lg:grid-cols-2 justify-items-center xl:grid-cols-3'>
        {ranking.map((player, index) => (
          <Card playerData={player} key={player.position} index={index} />
        ))}
      </div>
      <Footer />
    </>
  );
}

export async function getServerSideProps() {
  const res = await fetch('http://localhost:8080/ranking');
  const data = await res.json();

  return { props: { data } };
}
