import Head from 'next/head';
import { Footer, Card, Bar } from 'components';

if (process.env.NODE_ENV !== 'development') {
  // disable all console logs
  console.log = function () {};
}

export default function Home({ data }) {
  const getGMCutoff = () => {
    const master = data.filter((player) => player.tier !== 'GRANDMASTER');
    return parseInt(master[0].lp) + parseInt(master[0].lp_to_uprank);
  };

  return (
    <>
      <Head>
        <title>VININE Grandmaster Challenge</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <Bar GMLP={getGMCutoff()} />
      <div
        className='grid grid-col grid-cols-1 
       lg:grid-cols-2 justify-items-center xl:grid-cols-3 '
      >
        {data.map((player, index) => (
          <Card playerData={player} key={player.name} index={index} />
        ))}
      </div>
      <Footer />
    </>
  );
}

export async function getServerSideProps() {
  const url =
    process.env.NODE_ENV === 'development'
      ? 'http://localhost:8080/players'
      : 'https://vinine-grandmaster.herokuapp.com/players';

  const res = await fetch(url);
  const data = await res.json();

  return { props: { data } };
}
